title: "Automated Aircraft Detection in Satellite Imagery"
description: "Exploration of machine learning techniques for aircraft detection in satellite imagery. Course: A&O SCI-C111 / C204"
logo: "/assets/logo.png"
show_downloads: true
theme: jekyll-theme-cayman

